apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      containers:
      - name: frontend
        image: registry.github.com/job-app-tracker/frontend:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            ephemeral-storage: "2Gi"
          requests:
            memory: "256Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
      imagePullSecrets:
      - name: regcred
